name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-gym:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -e .
  
  build-ros:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -e ./model-gym-ros-env/car_node/car_node

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Build Docker image
      run: |
        docker build .
