name: Deploy LaTeX

on:
  push:
    paths:
      - "report/**"

jobs:
  Setup-Compile-Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DanySK/compile-and-publish-all-latex@2.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
